[package]
name = "barnacle"
version = "0.1.0"

[dependencies]
clap = "2"
config = "0.9"
csv = "1.1"
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
walkdir = "2"
yaml-rust = "0.4"
